spring.datasource.url=jdbc:mysql://localhost:3306/OOP_Real_state?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# Serve frontend static files from the workspace frontend folder
spring.web.resources.static-locations=file:C:/Users/saki/Desktop/OOP-Group_Project/frontend/
